general:
  name: scene0000_00_pretrain_test
  clean_up_folder_if_exists: True

model:
  pretrained: False
  pretrained_backbone: True
  load_checkpoint: True
  checkpoint_path: pretrain_25k/best-epoch143-step175536.ckpt
  num_classes: 40 # Scannet (40)

lr_scheduler:
  active: false

optimizer:
  lr_seg: 1.0e-5
  lr_nerf: 1.0e-2
  name: Adam

trainer:
  max_epochs: 150
  accelerator: 'gpu'
  num_sanity_val_steps: 0
  check_val_every_n_epoch: 1

data_module:
  pin_memory: true
  batch_size: 4
  shuffle: true
  num_workers: 0
  drop_last: true
  root: scannet_frames_25k
  data_preprocessing:
    val_ratio: 0.2
    image_regex: /*/color/*.jpg
    split_file: split.npz
    split_file_cl: split_cl.npz

visualizer:
  store: true
  store_n:
    train: 3
    val: 5000
    test: 5000

scenes:
  - scene0000_00
  - scene0001_00
  - scene0002_00
  - scene0003_00
  - scene0004_00
  - scene0005_00
  - scene0006_00
  - scene0007_00
  - scene0008_00
  - scene0009_00

cl:
 active: false
 use_novel_viewpoints: False
 replay_buffer_size: 0

